import { Contact } from './types';

export const generateMockContacts = (): Contact[] => [
  {
    id: '1',
    name: 'Craig Federighi',
    email: 'hairforceone@apple.com',
    currentPhoto: null,
    proposedPhoto: 'https://picsum.photos/seed/craig/200',
    source: 'google',
    status: 'pending',
    selected: true,
  },
  {
    id: '2',
    name: 'Tim Cook',
    email: 'tcook@apple.com',
    currentPhoto: 'https://picsum.photos/seed/timold/200',
    proposedPhoto: 'https://picsum.photos/seed/timnew/200',
    source: 'facebook',
    status: 'pending',
    selected: true,
  },
  {
    id: '3',
    name: 'Jony Ive',
    email: 'jony@lovefrom.com',
    currentPhoto: 'https://picsum.photos/seed/jony/200',
    proposedPhoto: null,
    source: null,
    status: 'pending',
    selected: false,
  },
  {
    id: '4',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    currentPhoto: null,
    proposedPhoto: 'https://picsum.photos/seed/jane/200',
    source: 'google',
    status: 'pending',
    selected: true,
  },
  {
    id: '5',
    name: 'John Smith',
    email: 'john.smith@example.com',
    currentPhoto: 'https://picsum.photos/seed/johnold/200',
    proposedPhoto: 'https://picsum.photos/seed/johnnew/200',
    source: 'facebook',
    status: 'pending',
    selected: true,
  },
  {
    id: '6',
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    currentPhoto: null,
    proposedPhoto: 'https://picsum.photos/seed/alice/200',
    source: 'google',
    status: 'pending',
    selected: true,
  },
  {
    id: '7',
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    currentPhoto: 'https://picsum.photos/seed/bob/200',
    proposedPhoto: 'https://picsum.photos/seed/bob/200', // Same photo, shouldn't need sync ideally, but for demo we show it
    source: 'facebook',
    status: 'pending',
    selected: false,
  }
];
